sudo: false
virtualenv:
  system_site_packages: true
language: c
addons:
  apt:
    packages:
    - cmake
    - lcov
cache:
  directories:
  - sprng2.0
  - mpich
before_install:
  - gem install coveralls-lcov
  - sh ./utilities/get_cgreen.sh
  - sh ./utilities/get_sprng.sh
script:
  - export CGREEN_CHILD_EXIT_WITH_FLUSH=TRUE
  - mkdir -p build
  - cd build
  - cmake -DWITH_CXX=OFF -DWITH_UNIT_TESTS=OFF -DBL_BUILD_TESTS=ON -DBL_ENABLE_COVERAGE=ON -DBL_WITH_PEDANTIC_FLAGS=OFF -DBL_WITH_WALL_FLAGS=ON ..
  - make -j2
  - ctest -j2 --output-on-failure
after_success:
  - lcov -d tests -d src -base-directory .. -c -o coverage.info
  - lcov --remove coverage.info '/usr/*' -o coverage.info
  - lcov --remove coverage.info 'cgreen/*' -o coverage.info
  - lcov --remove coverage.info 'tests/*' -o coverage.info
  - cd ..
  - coveralls-lcov build/coverage.info
